
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  password: 'password',
  isActive: 'isActive',
  isVerified: 'isVerified',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  avatar: 'avatar',
  department: 'department',
  designation: 'designation',
  failedLoginAttempts: 'failedLoginAttempts',
  isLocked: 'isLocked',
  lastLogin: 'lastLogin',
  lockedUntil: 'lockedUntil',
  name: 'name',
  passwordHistory: 'passwordHistory',
  passwordVersion: 'passwordVersion',
  userType: 'userType',
  employeeId: 'employeeId',
  joiningDate: 'joiningDate',
  phone: 'phone'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  token: 'token',
  refreshToken: 'refreshToken',
  device: 'device',
  browser: 'browser',
  os: 'os',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  loginAt: 'loginAt',
  lastActivity: 'lastActivity',
  expiresAt: 'expiresAt',
  idleExpiresAt: 'idleExpiresAt',
  isRevoked: 'isRevoked',
  revokedAt: 'revokedAt',
  isRememberMe: 'isRememberMe'
};

exports.Prisma.RefreshTokenScalarFieldEnum = {
  id: 'id',
  tokenHash: 'tokenHash',
  sessionId: 'sessionId',
  userId: 'userId',
  expiresAt: 'expiresAt',
  isRevoked: 'isRevoked',
  revokedAt: 'revokedAt',
  replacedByTokenHash: 'replacedByTokenHash'
};

exports.Prisma.RoleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  permissions: 'permissions',
  isSystem: 'isSystem',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  sessionId: 'sessionId',
  action: 'action',
  resource: 'resource',
  resourceId: 'resourceId',
  metadata: 'metadata',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  createdAt: 'createdAt'
};

exports.Prisma.LoginAttemptScalarFieldEnum = {
  id: 'id',
  email: 'email',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  success: 'success',
  failureReason: 'failureReason',
  lockedUntil: 'lockedUntil',
  createdAt: 'createdAt'
};

exports.Prisma.TaskScalarFieldEnum = {
  id: 'id',
  taskId: 'taskId',
  title: 'title',
  description: 'description',
  assignedUserId: 'assignedUserId',
  assignedUserName: 'assignedUserName',
  createdById: 'createdById',
  createdByName: 'createdByName',
  startDate: 'startDate',
  dueDate: 'dueDate',
  reminderDate: 'reminderDate',
  completedAt: 'completedAt',
  verifiedAt: 'verifiedAt',
  closedAt: 'closedAt',
  priority: 'priority',
  category: 'category',
  progress: 'progress',
  estimatedHours: 'estimatedHours',
  timeSpent: 'timeSpent',
  verifiedByName: 'verifiedByName',
  notes: 'notes',
  internalNotes: 'internalNotes',
  tags: 'tags',
  createdById_field: 'createdById_field',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  deletedById: 'deletedById',
  archivedAt: 'archivedAt',
  isArchived: 'isArchived',
  parentTaskId: 'parentTaskId',
  slaBreached: 'slaBreached',
  slaDueDate: 'slaDueDate',
  assignedById: 'assignedById',
  assignedByName: 'assignedByName',
  completedById: 'completedById',
  completedByName: 'completedByName',
  isFavorite: 'isFavorite',
  isPinned: 'isPinned',
  updatedById: 'updatedById',
  verifiedById: 'verifiedById',
  status: 'status',
  startedAt: 'startedAt'
};

exports.Prisma.TaskChecklistScalarFieldEnum = {
  id: 'id',
  taskId: 'taskId',
  text: 'text',
  completed: 'completed',
  completedAt: 'completedAt',
  completedBy: 'completedBy',
  order: 'order',
  createdAt: 'createdAt'
};

exports.Prisma.TaskCommentScalarFieldEnum = {
  id: 'id',
  taskId: 'taskId',
  content: 'content',
  authorId: 'authorId',
  authorName: 'authorName',
  isInternal: 'isInternal',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  isDeleted: 'isDeleted',
  mentions: 'mentions'
};

exports.Prisma.TaskAttachmentScalarFieldEnum = {
  id: 'id',
  taskId: 'taskId',
  fileName: 'fileName',
  fileType: 'fileType',
  fileSize: 'fileSize',
  fileUrl: 'fileUrl',
  uploadedBy: 'uploadedBy',
  uploadedByName: 'uploadedByName',
  description: 'description',
  createdAt: 'createdAt'
};

exports.Prisma.TaskDependencyScalarFieldEnum = {
  id: 'id',
  taskId: 'taskId',
  dependsOnTaskId: 'dependsOnTaskId',
  relationship: 'relationship',
  createdAt: 'createdAt'
};

exports.Prisma.TaskActivityLogScalarFieldEnum = {
  id: 'id',
  taskId: 'taskId',
  activityType: 'activityType',
  description: 'description',
  performedBy: 'performedBy',
  performedByName: 'performedByName',
  metadata: 'metadata',
  createdAt: 'createdAt'
};

exports.Prisma.LabelScalarFieldEnum = {
  id: 'id',
  name: 'name',
  color: 'color',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TaskLabelScalarFieldEnum = {
  id: 'id',
  taskId: 'taskId',
  labelId: 'labelId'
};

exports.Prisma.TaskWatcherScalarFieldEnum = {
  id: 'id',
  taskId: 'taskId',
  userId: 'userId',
  createdAt: 'createdAt'
};

exports.Prisma.TimeEntryScalarFieldEnum = {
  id: 'id',
  taskId: 'taskId',
  userId: 'userId',
  description: 'description',
  startedAt: 'startedAt',
  endedAt: 'endedAt',
  duration: 'duration',
  createdAt: 'createdAt'
};

exports.Prisma.DepartmentScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  managerId: 'managerId',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  isDeleted: 'isDeleted'
};

exports.Prisma.DepartmentMemberScalarFieldEnum = {
  id: 'id',
  departmentId: 'departmentId',
  userId: 'userId',
  role: 'role',
  createdAt: 'createdAt'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  title: 'title',
  message: 'message',
  taskId: 'taskId',
  isRead: 'isRead',
  readAt: 'readAt',
  createdAt: 'createdAt'
};

exports.Prisma.SavedFilterScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  name: 'name',
  filters: 'filters',
  isShared: 'isShared',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CustomViewScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  name: 'name',
  viewType: 'viewType',
  filters: 'filters',
  sortBy: 'sortBy',
  sortOrder: 'sortOrder',
  columns: 'columns',
  isShared: 'isShared',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AutomationRuleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  trigger: 'trigger',
  conditions: 'conditions',
  actions: 'actions',
  isActive: 'isActive',
  runCount: 'runCount',
  lastRunAt: 'lastRunAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TaskTemplateScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  defaults: 'defaults',
  createdById: 'createdById',
  useCount: 'useCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ActivityFeedScalarFieldEnum = {
  id: 'id',
  entityType: 'entityType',
  entityId: 'entityId',
  activityType: 'activityType',
  description: 'description',
  performedBy: 'performedBy',
  performedByName: 'performedByName',
  metadata: 'metadata',
  createdAt: 'createdAt'
};

exports.Prisma.NoteScalarFieldEnum = {
  id: 'id',
  title: 'title',
  content: 'content',
  folder: 'folder',
  tags: 'tags',
  isPinned: 'isPinned',
  isArchived: 'isArchived',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt'
};

exports.Prisma.AppVersionScalarFieldEnum = {
  id: 'id',
  version: 'version',
  platform: 'platform',
  buildNumber: 'buildNumber',
  fileUrl: 'fileUrl',
  fileSize: 'fileSize',
  fileName: 'fileName',
  fileType: 'fileType',
  releaseNotes: 'releaseNotes',
  isLatest: 'isLatest',
  isStable: 'isStable',
  downloadCount: 'downloadCount',
  uploadedBy: 'uploadedBy',
  uploadedByName: 'uploadedByName',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.UserRole = exports.$Enums.UserRole = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  EMPLOYEE: 'EMPLOYEE'
};

exports.UserType = exports.$Enums.UserType = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  EMPLOYEE: 'EMPLOYEE'
};

exports.TaskPriority = exports.$Enums.TaskPriority = {
  None: 'None',
  Low: 'Low',
  Medium: 'Medium',
  High: 'High',
  Urgent: 'Urgent'
};

exports.TaskCategory = exports.$Enums.TaskCategory = {
  General: 'General',
  Office: 'Office',
  FieldWork: 'FieldWork',
  Maintenance: 'Maintenance',
  Installation: 'Installation',
  Inspection: 'Inspection',
  Documentation: 'Documentation',
  Meeting: 'Meeting',
  Training: 'Training',
  Other: 'Other'
};

exports.TaskStatus = exports.$Enums.TaskStatus = {
  Draft: 'Draft',
  Todo: 'Todo',
  InProgress: 'InProgress',
  OnHold: 'OnHold',
  Completed: 'Completed',
  Archived: 'Archived',
  Cancelled: 'Cancelled'
};

exports.NotificationType = exports.$Enums.NotificationType = {
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  TASK_VERIFIED: 'TASK_VERIFIED',
  TASK_REJECTED: 'TASK_REJECTED',
  COMMENT_ADDED: 'COMMENT_ADDED',
  MENTION: 'MENTION',
  STATUS_CHANGED: 'STATUS_CHANGED',
  DUE_DATE_REMINDER: 'DUE_DATE_REMINDER',
  SLA_BREACH: 'SLA_BREACH'
};

exports.Prisma.ModelName = {
  User: 'User',
  Session: 'Session',
  RefreshToken: 'RefreshToken',
  Role: 'Role',
  AuditLog: 'AuditLog',
  LoginAttempt: 'LoginAttempt',
  Task: 'Task',
  TaskChecklist: 'TaskChecklist',
  TaskComment: 'TaskComment',
  TaskAttachment: 'TaskAttachment',
  TaskDependency: 'TaskDependency',
  TaskActivityLog: 'TaskActivityLog',
  Label: 'Label',
  TaskLabel: 'TaskLabel',
  TaskWatcher: 'TaskWatcher',
  TimeEntry: 'TimeEntry',
  Department: 'Department',
  DepartmentMember: 'DepartmentMember',
  Notification: 'Notification',
  SavedFilter: 'SavedFilter',
  CustomView: 'CustomView',
  AutomationRule: 'AutomationRule',
  TaskTemplate: 'TaskTemplate',
  ActivityFeed: 'ActivityFeed',
  Note: 'Note',
  AppVersion: 'AppVersion'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
