/**
 * Shared system configuration for a fresh installation.
 * Used by seed-system / seed-reset-system and registration bootstrap.
 * Task Management — role permission defaults only.
 */
export const SYSTEM_ROLE_DEFS = [
  { name: 'Owner', permissions: ['*'] as string[] },
  {
    name: 'Admin',
    permissions: [
      'task:list',
      'task:read',
      'task:create',
      'task:update',
      'task:delete',
      'task:restore',
      'task:approve',
      'user:list',
      'user:read',
      'user:create',
      'user:update',
      'user:delete',
      'role:list',
      'role:read',
      'role:create',
      'role:update',
      'organization:read',
      'organization:update',
      'department:list',
      'department:create',
      'department:update',
      'department:delete',
      'team:list',
      'team:create',
      'team:update',
      'team:delete',
      'label:list',
      'label:create',
      'label:update',
      'label:delete',
      'template:list',
      'template:create',
      'template:update',
      'template:delete',
      'automation:list',
      'automation:create',
      'automation:update',
      'automation:delete',
      'report:view',
      'report:export',
      'salary:read',
      'salary:create',
      'salary:update',
      'salary:delete',
      'salary:approve',
      'tracking:read',
      'tracking:update',
      'settings:read',
      'settings:update',
      'auth:read',
      'auth:update',
    ],
  },
  {
    name: 'Manager',
    permissions: [
      'task:list',
      'task:read',
      'task:create',
      'task:update',
      'task:approve',
      'user:list',
      'user:read',
      'department:list',
      'team:list',
      'label:list',
      'template:list',
      'report:view',
      'salary:read',
      'tracking:read',
      'tracking:update',
      'settings:read',
      'auth:read',
    ],
  },
  {
    name: 'Employee',
    permissions: [
      'task:list',
      'task:read',
      'task:create',
      'task:update',
      'label:list',
      'template:list',
      'settings:read',
      'auth:read',
      'salary:read',
    ],
  },
] as const;

export const EVENT_RULES: Record<string, any[]> = {};
